name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip zip unzip openjdk-17-jdk wget git libncurses6 libstdc++6 zlib1g
          pip install --upgrade pip
          pip install buildozer cython

      - name: Set up Android SDK
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip
          mv cmdline-tools latest
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;34.0.0" \
            "cmdline-tools;latest" \
            "extras;android;m2repository" \
            "extras;google;m2repository"

      - name: Verify AIDL
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/build-tools/34.0.0:$ANDROID_HOME/platform-tools:$PATH
          if ! command -v aidl &> /dev/null; then
            echo "AIDL not found, linking it..."
            sudo ln -s $ANDROID_HOME/build-tools/34.0.0/aidl /usr/local/bin/aidl || true
          fi
          echo "AIDL found at: $(which aidl)"
          aidl --version || echo "AIDL ready!"

      - name: Build APK
        env:
          ANDROID_HOME: $HOME/android-sdk
          PATH: $HOME/android-sdk/build-tools/34.0.0:$HOME/android-sdk/platform-tools:$HOME/android-sdk/cmdline-tools/latest/bin:$PATH
          REPO_OS_OVERRIDE: "linux"
        run: |
          echo "Checking tools..."
          git --version
          aidl --version || echo "AIDL working"
          echo "Building APK now..."
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Vaishu-Calculator-APK
          path: bin/*.apk
